import "./modules/page-loading.js";
import "./modules/modernizr.js";
import "./modules/animations/header.js";
import "./modules/limitStr.js";
import "./modules/nav.js";
import "./modules/anchor-links.js";
import "./modules/form-submit.js";
import "./modules/msnry.js";
import "./modules/custom-select.js";
import "./modules/input-number-mask.js";
import "./modules/swiper.js";
import "./modules/fancybox.js";
import "./modules/yMaps.js";
import "./modules/modal-init.js"
